#!/bin/bash

HAHII="∥￣口￣∥　はひー"

if [ ! -e ~/.akari_hahii.tmp ]; then
	echo 1 > ~/.akari_hahii.tmp
fi
COUNT=`cat ~/.akari_hahii.tmp`

if [ $# == 0 ]; then
	MSG=""
else
	MSG=" | $*"
fi


tw -yes "${HAHII} (${COUNT}回目)${MSG}" > /dev/null
#tw -yes "${HAHII} (`date +%H:%M:%S`)" > /dev/null

echo "${COUNT} +1" | bc > ~/.akari_hahii.tmp
