#! /bin/bash

buildsh="build.sh"
exefile=$buildsh

if [ $# == 1 ] ; then
	exefile=$1.sh
fi

tryrun() {
	if [ -e .$buildsh -o -e $buildsh -o -e ,$buildsh ] ; then
		for prefix in ',' '' '.' ; do
			if [ -e $prefix$exefile ] ; then
				if [ '#!' == `head --bytes=2 $prefix$exefile` ] ; then
					chmod a+x ./$prefix$exefile >/dev/null 2>&1
					./$prefix$exefile
				else
					sh ./$prefix$exefile
				fi
				exit
			fi
		done
	fi
}

cd `pwd -P`

while [ "/" != `pwd` ] ; do
	tryrun
	cd ..
done
tryrun

echo "not exist \"$exefile\"."
