#! /bin/bash

gitStatus()
{
	echo ' - - - - - - - - - - - - - - - - - - - - '
	git status
	return 0
}

ENV_SSH=1

ssh-add -l
if [ $? == 2 ] ; then
	ENV_SSH=0
	eval `ssh-agent -s`
	ssh-add
elif [ $? == 1 ] ; then
	ssh-add
fi

git pull

if [ $# == 0 ] ; then
	gitStatus
	exit
fi

git pull
git add ./
git commit -am "$*"
git push
gitStatus

if [ $ENV_SSH == 0 ] ; then
	eval `ssh-agent -sk`
fi
