#! /bin/bash

gitStatus()
{
	echo
	if [[ `git status` =~ "nothing to commit, working directory clean" ]]; then
		echo -e "\e[42m"
	else
		echo -e "\e[41m"
	fi
	SPACE=`tput cols`
	printf "%.${SPACE}s" "                                                                                                                                                                                                                                                                                                            "
	echo -e "\e[m"
	return 0
}

ENV_SSH=1

ssh-add -l
SSHL=$?
if [ $SSHL == 2 ] ; then
	ENV_SSH=0
	eval `ssh-agent -s`
	ssh-add
elif [ $SSHL == 1 ] ; then
	ssh-add
fi

git pull

if [ $# == 0 ] ; then
	gitStatus
	exit
fi

git pull
git add ./
git commit -am "$*"
git push

if [ $ENV_SSH == 0 ] ; then
	eval `ssh-agent -sk`
fi

gitStatus
